### ISSUE TITLE
[Error] Building yojimbo gmake2 mingw 

### ISSUE THREAD

**Issue by UsmanTariq2** [mas-bandwidth/yojimbo#199]
`"sodium_randombytes.c"
"sodium_randombytes_salsa20_random.c"
sodium/sodium_randombytes_salsa20_random.c:120:8: error: unknown attribute 'thread' ignored
      [-Werror,-Wunknown-attributes]
  120 | static TLS Salsa20Random stream;
      |        ^~~
sodium/sodium_randombytes_salsa20_random.c:94:26: note: expanded from macro 'TLS'
   94 | #  define TLS __declspec(thread)
      |                          ^~~~~~
<built-in>:389:38: note: expanded from macro '__declspec'
  389 | #define __declspec(a) __attribute__((a))`

I get the above error when building yojimbo using _mingw32-make_
Compiler Version : MINGW G++ 14

Issue present on master and latest stable release

**Comment by UsmanTariq2** [comment]
Also, is 64 supported , i see that for VS it is coded to x86.
Is x64 easy to switch to after some minor modifications?

**Comment by gafferongames** [comment]
64bit is supported

**Comment by UsmanTariq2** [comment]
Can u briefly guide how to set it up for 64 bit? I cannot find a resource.

**Comment by jclc** [comment]
The error (actually warning) in your post is easily fixed by replacing lines 92-98 with this from the latest libsodium:
```
#if !defined(TLS) && !defined(__STDC_NO_THREADS__) && \
    defined(__STDC_VERSION__) && __STDC_VERSION__ >= 201112L
# define TLS _Thread_local
#endif
#ifndef TLS
# ifdef _WIN32
#  define TLS __declspec(thread)
# else
#  define TLS
# endif
#endif
```
Assuming you're using at least C11.

However, linking ultimately fails with these undefined references:
```
/usr/lib/gcc/x86_64-w64-mingw32/14.2.0/../../../../x86_64-w64-mingw32/bin/ld: CMakeFiles/World.dir/external/yojimbo/netcode/netcode.c.obj:netcode.c:(.text+0xc10): undefined reference to `QOSCreateHandle'
/usr/lib/gcc/x86_64-w64-mingw32/14.2.0/../../../../x86_64-w64-mingw32/bin/ld: CMakeFiles/World.dir/external/yojimbo/netcode/netcode.c.obj:netcode.c:(.text+0xc3b): undefined reference to `QOSAddSocketToFlow'
```
I've tried to search for a link option to fix these but I can't seem to find any useful information on this... Linking with `ws2_32` or `wsock32` doesn't seem to help.

**Comment by gafferongames** [comment]
The QOS stuff is due to packet tagging on IPv6, you can disable this by commenting out the line

#define PACKET_TAGGING 1

Alternatively, you could just comment out the code around the usage of QOSCreateHandle and you'll just disable packet tagging on IPv6 only for Mingw.

alternatively, the symbols should be found in this lib:

#pragma comment( lib, "Qwave.lib" )

Which does not seem to be up to date on MingW?

**Comment by jclc** [comment]
Thanks for the information. Disabling packet tagging makes it work, but it required a few changes to make yojimbo compile. I'll see if I can make a PR with a fix this week.

**Comment by gafferongames** [comment]
Thanks! What would be most helpful is if you could also create a PR for netcode so you detect MingGW and it compiles (here: https://github.com/mas-bandwidth/netcode) because otherwise this fix may get lost the next time netcode is copied into Yojimbo source.
