### ISSUE TITLE
C API

### ISSUE THREAD

**Issue by a-day-old-bagel** [mas-bandwidth/yojimbo#219]
Hi, I'm a huge fan of all your old networked physics articles (and your assorted blogs and articles in general)

I've never tried using yojimbo, but from what I can tell, it's only designed to be used from C++, correct?

I see that years ago, #24 was brought up about language bindings, and at that time, they didn't seem pertinent, as I understand the response.

Anyway, I wanted to re-evaluate the question, and ask if you're at all interested in supporting a C API.

If you already have one somewhere here that I'm not seeing, forgive my ignorance.

**Comment by gafferongames** [comment]
I don't think this is really possible. Yojimbo will remain C++, primarily because the serialization (which is integral to the library and creating new message and data types) is C++ specific.

I'm taking the  key parts of serialize, reliable, netcode and Yojimbo and re-imagining them as a C-only library from the ground up here:

https://github.com/mas-bandwidth/snapshot

No promises when this will be ready....
